export const ALL_CONSUMER_ACCOUNTS = 'ALL_CONSUMER_ACCOUNTS';

export const CONSUMER_PERSONAL_INFO = 'CONSUMER_PERSONAL_INFO';

export const ACCOUNT_SUMMARY_CONSUMER_DATA = 'ACCOUNT_SUMMARY_CONSUMER_DATA';

export const CONSUMER_DEMOGRAPHICS = 'CONSUMER_DEMOGRAPHICS';

export const SEARCH_CONSUMER_DATA = 'SEARCH_CONSUMER_DATA';

export const EDIT_CONSUMER = 'EDIT_CONSUMER';

export const EDIT_CONSUMER_INPUTS = 'EDIT_CONSUMER_INPUTS';

export const EDIT_EMPLOYER_INPUTS = 'EDIT_EMPLOYER_INPUTS';

export const SETCUSTOMERID = 'SETCUSTOMERID';

export const ADD_EMPLOYER_INPUTS = 'ADD_EMPLOYER_INPUTS';

export const CONSUMER_EMPLOYERS = 'CONSUMER_EMPLOYERS';

export const RELATIONSHIP_TYPES_DATA = 'RELATIONSHIP_TYPES_DATA';

export const ALL_NOTES = 'ALL_NOTES';

export const ALERT_LIST = 'ALERT_LIST';

export const SAVE_PORTFOLIO_ID = 'SAVE_PORTFOLIO_ID';

export const CONSUMER_VERIFICATION = 'CONSUMER_VERIFICATION';

export const CONSUMER_SKIP_VERIFICATION = 'CONSUMER_SKIP_VERIFICATION';

export const VERIFICATION_QUESTIONNAIRE = 'VERIFICATION_QUESTIONNAIRE';

export const SPOKETO_LIST = 'SPOKETO_LIST';

export const OLD_SPOKETO_LIST = 'OLD_SPOKETO_LIST';

export const ADD_CALLWRAPUPNOTE_INPUTS = 'ADD_CALLWRAPUPNOTE_INPUTS';

export const RESET_AFTER_SPOKE_TO_CHANGE = 'RESET_AFTER_SPOKE_TO_CHANGE';

export const SUBMIT_FORM_CALL = 'SUBMIT_FORM_CALL';

export const ALL_CONSUMER_ACCOUNTS_FOR_CALLWRAPUP = 'ALL_CONSUMER_ACCOUNTS_FOR_CALLWRAPUP';

export const ACCOUNT_GENERAL_INFO = 'ACCOUNT_GENERAL_INFO';

export const ACCOUNT_SUMMARY_INFO = 'ACCOUNT_SUMMARY_INFO';

export const ACCOUNT_LEFT_MENU_INFO = 'ACCOUNT_LEFT_MENU_INFO';

export const CURRENT_ACCOUNT_NUMBER = 'CURRENT_ACCOUNT_NUMBER';

export const SINGLE_PAYMENT_INFO = 'SINGLE_PAYMENT_INFO';

export const CURRENT_ACCOUNT_SET = 'CURRENT_ACCOUNT_SET';

export const GET_EMPLOYMENT_TYPES = 'GET_EMPLOYMENT_TYPES';

export const ACCOUNT_SUB_BALANACE_TYPE = 'ACCOUNT_SUB_BALANACE_TYPE';

export const ACCOUNT_BALANACE = 'ACCOUNT_BALANACE';

export const SAVE_DEPENDENTS_OF_ACCOUNT = 'SAVE_DEPENDENTS_OF_ACCOUNT';

export const SAVE_RESPONSIBLES = 'SAVE_RESPONSIBLES';

export const RESET_ALL = 'RESET_ALL';

export const DECEASED_INFO = 'DECEASED_INFO';

export const ADD_DECEASED_INPUTS = 'ADD_DECEASED_INPUTS';

export const CONSUMER_ALIASES = 'CONSUMER_ALIASES';

export const ALIAS_TYPES = 'ALIAS_TYPES';

export const ADD_COURT_INPUTS = 'ADD_COURT_INPUTS';

export const ADD_EXECUTOR_INPUTS = 'ADD_EXECUTOR_INPUTS';

export const EDIT_DECEASED = 'EDIT_DECEASED';

export const DELETE_DECEASED = 'DELETE_DECEASED';

export const LIST_ACTIVE_CONTIGENCYFEE = 'LIST_ACTIVE_CONTIGENCYFEE';

export const GET_ACCOUNT_FINANCIAL_DETAILS = 'GET_ACCOUNT_FINANCIAL_DETAILS';

export const UPDATE_ACCOUNT_FINANCIAL_DETAILS = 'UPDATE_ACCOUNT_FINANCIAL_DETAILS';

export const KPI_DETAILS = 'KPI_DETAILS';

export const QUEUE_DETAILS = "QUEUE_DETAILS";