export const SAVE_COUNTRIES = "SAVE_COUNTRIES";

export const SAVE_STATES = "SAVE_STATES";

export const SAVE_STATES_ON_LOAD = "SAVE_STATES_ON_LOAD"

export const ADD_ALERT_INPUTS = "ADD_ALERT_INPUTS";

export const ALERT_TYPES = "ALERT_TYPES";

export const VIEW_CALL_WRAPUP_DATA = "VIEW_CALL_WRAPUP_DATA";

export const VIEW_CALL_METHODS = "VIEW_CALL_METHODS";

export const ADD_CALL_WRAPUP_INPUTS = "ADD_CALL_WRAPUP_INPUTS";

export const GET_STATES = "GET_STATES";

export const PREFERED_LANGUAGES = "PREFERED_LANGUAGES";

export const  CONSUMER_DEMOGRAPHIC_SOURCE = "CONSUMER_DEMOGRAPHIC_SOURCE";

export const DISPUTE_REASONS = "DISPUTE_REASONS"

export const BANKRUPTCY_TYPE = "BANKRUPTCY_TYPE";

export const COMPLAINTS_TYPES = "COMPLAINTS_TYPES";

export const CUSTOMFIELD_LOCATIONS = "CUSTOMFIELD_LOCATIONS";

export const CUSTOMFIELD_DATATYPE = "CUSTOMFIELD_DATATYPE";
