export const response1 = {
  data: [
    {
      accountNum: null,
      asGather: false,
      asSubFlow: false,
      auditInstanceId: null,
      auditResult: null,
      auditingFinishedDate: null,
      auditingRemediateDate: null,
      auditingRemediated: null,
      auditingStartBy: null,
      auditingStartDate: "Jan 15 2022",
      auditingStatus: null,
      canAccessAudit: null,
      canContinue: false,
      canStart: true,
      cancelBy: null,
      cls: " flow-folder",
      curAuditStepId: null,
      curStepId: null,
      entryDate: null,
      exitDate: null,
      expanded: true,
      flowId: null,
      id: null,
      inBulk: false,
      instanceId: null,
      leaf: false,
      name: null,
      originalAccountNumber: null,
      pageType: null,
      persistenceCode: null,
      priority: null,
      responsibleId: null,
      scheduleActiveDate: null,
      scheduleId: 1743,
      scheduleName: null,
      scheduleStatus: "ACTIVE",
      startBy: null,
      status: null,
      stepProgress: null,
      stuckOnTask: null,
      synchronize: false,
      text: "Servicing Demo_V49",
      triggeredSurveyFlow: false,
      type: "SurveySchedule",
    },
    {
      accountNum: null,
      asGather: false,
      asSubFlow: false,
      auditInstanceId: null,
      auditResult: null,
      auditingFinishedDate: null,
      auditingRemediateDate: null,
      auditingRemediated: null,
      auditingStartBy: null,
      auditingStartDate: "June 19,2022",
      auditingStatus: null,
      canAccessAudit: null,
      canContinue: false,
      canStart: false,
      cancelBy: null,
      cls: " flow-folder",
      curAuditStepId: null,
      curStepId: null,
      entryDate: null,
      exitDate: null,
      expanded: true,
      flowId: null,
      id: null,
      inBulk: false,
      instanceId: null,
      leaf: false,
      name: null,
      originalAccountNumber: null,
      pageType: null,
      persistenceCode: null,
      priority: null,
      responsibleId: null,
      scheduleActiveDate: null,
      scheduleId: 1744,
      scheduleName: null,
      scheduleStatus: "ACTIVE",
      startBy: null,
      status: "Pending",
      stepProgress: null,
      stuckOnTask: null,
      synchronize: false,
      text: "Expense Sample",
      triggeredSurveyFlow: false,
      type: "SurveySchedule",
    },
    {
      accountNum: null,
      asGather: false,
      asSubFlow: false,
      auditInstanceId: null,
      auditResult: null,
      auditingFinishedDate: "June 30,2022",
      auditingRemediateDate: null,
      auditingRemediated: null,
      auditingStartBy: "Karthik",
      auditingStartDate: "June 1,2022",
      auditingStatus: null,
      canAccessAudit: null,
      canContinue: false,
      canStart: false,
      cancelBy: null,
      cls: " flow-folder",
      curAuditStepId: null,
      curStepId: null,
      entryDate: null,
      exitDate: null,
      expanded: true,
      flowId: null,
      id: null,
      inBulk: false,
      instanceId: null,
      leaf: false,
      name: null,
      originalAccountNumber: null,
      pageType: null,
      persistenceCode: null,
      priority: null,
      responsibleId: null,
      scheduleActiveDate: null,
      scheduleId: 1745,
      scheduleName: null,
      scheduleStatus: "ACTIVE",
      startBy: null,
      status: "Completed",
      stepProgress: null,
      stuckOnTask: null,
      synchronize: false,
      text: "Review",
      triggeredSurveyFlow: false,
      type: "SurveySchedule",
    },
    {
      accountNum: null,
      asGather: false,
      asSubFlow: false,
      auditInstanceId: null,
      auditResult: null,
      auditingFinishedDate: null,
      auditingRemediateDate: null,
      auditingRemediated: null,
      auditingStartBy: null,
      auditingStartDate: null,
      auditingStatus: null,
      canAccessAudit: null,
      canContinue: false,
      canStart: false,
      cancelBy: null,
      cls: " flow-folder",
      curAuditStepId: null,
      curStepId: null,
      entryDate: null,
      exitDate: null,
      expanded: true,
      flowId: null,
      id: null,
      inBulk: false,
      instanceId: null,
      leaf: false,
      name: null,
      originalAccountNumber: null,
      pageType: null,
      persistenceCode: null,
      priority: null,
      responsibleId: null,
      scheduleActiveDate: null,
      scheduleId: 1746,
      scheduleName: null,
      scheduleStatus: "ACTIVE",
      startBy: null,
      status: null,
      stepProgress: null,
      stuckOnTask: null,
      synchronize: false,
      text: "Workflow",
      triggeredSurveyFlow: false,
      type: "SurveySchedule",
    },
    {
      accountNum: null,
      asGather: false,
      asSubFlow: false,
      auditInstanceId: null,
      auditResult: null,
      auditingFinishedDate: null,
      auditingRemediateDate: null,
      auditingRemediated: null,
      auditingStartBy: null,
      auditingStartDate: null,
      auditingStatus: null,
      canAccessAudit: null,
      canContinue: false,
      canStart: true,
      cancelBy: null,
      cls: " flow-folder",
      curAuditStepId: null,
      curStepId: null,
      entryDate: null,
      exitDate: null,
      expanded: true,
      flowId: null,
      id: null,
      inBulk: false,
      instanceId: null,
      leaf: false,
      name: null,
      originalAccountNumber: null,
      pageType: null,
      persistenceCode: null,
      priority: null,
      responsibleId: null,
      scheduleActiveDate: null,
      scheduleId: 1747,
      scheduleName: null,
      scheduleStatus: "ACTIVE",
      startBy: null,
      status: null,
      stepProgress: null,
      stuckOnTask: null,
      synchronize: false,
      text: "Method",
      triggeredSurveyFlow: false,
      type: "SurveySchedule",
    },
  ],
  message: "",
  success: true,
  total: 1,
  version: 1655307825520,
};

export const response2 = {
  data: [
    {
      accountNum: null,
      asGather: false,
      asSubFlow: false,
      auditInstanceId: null,
      auditResult: null,
      auditingFinishedDate: null,
      auditingRemediateDate: null,
      auditingRemediated: null,
      auditingStartBy: null,
      auditingStartDate: null,
      auditingStatus: null,
      canAccessAudit: false,
      canContinue: false,
      canStart: true,
      cancelBy: null,
      cls: " flow-folder",
      curAuditStepId: null,
      curStepId: null,
      entryDate: null,
      exitDate: null,
      expanded: true,
      flowId: 25255,
      id: "flow25255",
      inBulk: false,
      instanceId: null,
      leaf: false,
      name: "Build My Own Settlement",
      originalAccountNumber: null,
      pageType: null,
      persistenceCode: "",
      priority: 5,
      responsibleId: null,
      scheduleActiveDate: null,
      scheduleId: null,
      scheduleName: null,
      scheduleStatus: "ACTIVE",
      startBy: null,
      status: null,
      stepProgress: null,
      stuckOnTask: null,
      synchronize: false,
      text: "Build My Own Settlement",
      triggeredSurveyFlow: false,
      type: null,
    },
    {
      accountNum: null,
      asGather: false,
      asSubFlow: false,
      auditInstanceId: null,
      auditResult: null,
      auditingFinishedDate: null,
      auditingRemediateDate: null,
      auditingRemediated: null,
      auditingStartBy: null,
      auditingStartDate: null,
      auditingStatus: null,
      canAccessAudit: false,
      canContinue: false,
      canStart: true,
      cancelBy: null,
      cls: " flow-folder",
      curAuditStepId: null,
      curStepId: null,
      entryDate: null,
      exitDate: null,
      expanded: true,
      flowId: 25257,
      id: "flow25257",
      inBulk: false,
      instanceId: null,
      leaf: false,
      name: "Reposession",
      originalAccountNumber: null,
      pageType: null,
      persistenceCode: "",
      priority: 6,
      responsibleId: null,
      scheduleActiveDate: null,
      scheduleId: null,
      scheduleName: null,
      scheduleStatus: "ACTIVE",
      startBy: null,
      status: null,
      stepProgress: null,
      stuckOnTask: null,
      synchronize: false,
      text: "Reposession",
      triggeredSurveyFlow: false,
      type: null,
    },
    {
      accountNum: null,
      asGather: false,
      asSubFlow: false,
      auditInstanceId: null,
      auditResult: null,
      auditingFinishedDate: null,
      auditingRemediateDate: null,
      auditingRemediated: null,
      auditingStartBy: null,
      auditingStartDate: null,
      auditingStatus: null,
      canAccessAudit: false,
      canContinue: false,
      canStart: true,
      cancelBy: null,
      cls: " flow-folder",
      curAuditStepId: null,
      curStepId: null,
      entryDate: null,
      exitDate: null,
      expanded: true,
      flowId: 25265,
      id: "flow25265",
      inBulk: false,
      instanceId: null,
      leaf: false,
      name: "Legal Claim Workflow",
      originalAccountNumber: null,
      pageType: null,
      persistenceCode: "",
      priority: 10,
      responsibleId: null,
      scheduleActiveDate: null,
      scheduleId: null,
      scheduleName: null,
      scheduleStatus: "ACTIVE",
      startBy: null,
      status: null,
      stepProgress: null,
      stuckOnTask: null,
      synchronize: false,
      text: "Legal Claim Workflow",
      triggeredSurveyFlow: false,
      type: null,
    },
    {
      accountNum: null,
      asGather: false,
      asSubFlow: false,
      auditInstanceId: null,
      auditResult: null,
      auditingFinishedDate: null,
      auditingRemediateDate: null,
      auditingRemediated: null,
      auditingStartBy: null,
      auditingStartDate: null,
      auditingStatus: null,
      canAccessAudit: false,
      canContinue: false,
      canStart: true,
      cancelBy: null,
      cls: " flow-folder",
      curAuditStepId: null,
      curStepId: null,
      entryDate: null,
      exitDate: null,
      expanded: true,
      flowId: 25267,
      id: "flow25267",
      inBulk: false,
      instanceId: null,
      leaf: false,
      name: "Legal Judgment Workflow",
      originalAccountNumber: null,
      pageType: null,
      persistenceCode: "",
      priority: 11,
      responsibleId: null,
      scheduleActiveDate: null,
      scheduleId: null,
      scheduleName: null,
      scheduleStatus: "ACTIVE",
      startBy: null,
      status: null,
      stepProgress: null,
      stuckOnTask: null,
      synchronize: false,
      text: "Legal Judgment Workflow",
      triggeredSurveyFlow: false,
      type: null,
    },
    {
      accountNum: null,
      asGather: false,
      asSubFlow: false,
      auditInstanceId: null,
      auditResult: null,
      auditingFinishedDate: null,
      auditingRemediateDate: null,
      auditingRemediated: null,
      auditingStartBy: null,
      auditingStartDate: null,
      auditingStatus: null,
      canAccessAudit: false,
      canContinue: false,
      canStart: true,
      cancelBy: null,
      cls: " flow-folder",
      curAuditStepId: null,
      curStepId: null,
      entryDate: null,
      exitDate: null,
      expanded: true,
      flowId: 25269,
      id: "flow25269",
      inBulk: false,
      instanceId: null,
      leaf: false,
      name: "Additional Court Fee Workflow",
      originalAccountNumber: null,
      pageType: null,
      persistenceCode: "",
      priority: 12,
      responsibleId: null,
      scheduleActiveDate: null,
      scheduleId: null,
      scheduleName: null,
      scheduleStatus: "ACTIVE",
      startBy: null,
      status: null,
      stepProgress: null,
      stuckOnTask: null,
      synchronize: false,
      text: "Additional Court Fee Workflow",
      triggeredSurveyFlow: false,
      type: null,
    },
    {
      accountNum: null,
      asGather: false,
      asSubFlow: false,
      auditInstanceId: null,
      auditResult: null,
      auditingFinishedDate: null,
      auditingRemediateDate: null,
      auditingRemediated: null,
      auditingStartBy: null,
      auditingStartDate: null,
      auditingStatus: null,
      canAccessAudit: false,
      canContinue: false,
      canStart: true,
      cancelBy: null,
      cls: " flow-folder",
      curAuditStepId: null,
      curStepId: null,
      entryDate: null,
      exitDate: null,
      expanded: true,
      flowId: 25271,
      id: "flow25271",
      inBulk: false,
      instanceId: null,
      leaf: false,
      name: "Bureau Correction",
      originalAccountNumber: null,
      pageType: null,
      persistenceCode: "",
      priority: 13,
      responsibleId: null,
      scheduleActiveDate: null,
      scheduleId: null,
      scheduleName: null,
      scheduleStatus: "ACTIVE",
      startBy: null,
      status: null,
      stepProgress: null,
      stuckOnTask: null,
      synchronize: false,
      text: "Bureau Correction",
      triggeredSurveyFlow: false,
      type: null,
    },
    {
      accountNum: null,
      asGather: false,
      asSubFlow: false,
      auditInstanceId: null,
      auditResult: null,
      auditingFinishedDate: null,
      auditingRemediateDate: null,
      auditingRemediated: null,
      auditingStartBy: null,
      auditingStartDate: null,
      auditingStatus: null,
      canAccessAudit: false,
      canContinue: false,
      canStart: true,
      cancelBy: null,
      cls: " flow-folder",
      curAuditStepId: null,
      curStepId: null,
      entryDate: null,
      exitDate: null,
      expanded: true,
      flowId: 25273,
      id: "flow25273",
      inBulk: false,
      instanceId: null,
      leaf: false,
      name: "ReageProgram Offer",
      originalAccountNumber: null,
      pageType: null,
      persistenceCode: "",
      priority: 14,
      responsibleId: null,
      scheduleActiveDate: null,
      scheduleId: null,
      scheduleName: null,
      scheduleStatus: "ACTIVE",
      startBy: null,
      status: null,
      stepProgress: null,
      stuckOnTask: null,
      synchronize: false,
      text: "ReageProgram Offer",
      triggeredSurveyFlow: false,
      type: null,
    },
  ],
  message: "",
  success: true,
  total: 7,
  version: 1655307826115,
};

export const historicalSelect = {
  id: "3",
  type: "select",
  name: "typeId",
  label: "Type",
  spacing: 4,
  showOther: true,
  required: true,
  idaccessor: "id",
  valueaccessor: "code",
};

export const historicalOptions = [
  {
    id: "1",
    // name: "payment"
    code: "111",
    name: "Workflow History1",
    status: "Active",
    sdate: "11-2-2021",
    fdate: "",
    cdate: "12-4-2022",
    by: "Don",
    cby: "Zen",
  },
  {
    id: "2",
    // name: "Basic update"
    code: "222",
    name: "Workflow History2",
    status: "Draft",
    sdate: "11-2-2021",
    fdate: "16-10-2021",
    cdate: "12-4-2022",
    by: "Don",
    cby: "Sest",
  },
];

export const Headers = [
  {
    Header: "Persistence Code",
    accessor: "code",
  },
  {
    Header: "Status",
    accessor: "status",
  },
  {
    Header: "Started Date",
    accessor: "sdate",
  },
  {
    Header: "Finished Date",
    accessor: "fdate",
  },
  {
    Header: "Cancelled Date",
    accessor: "cdate",
  },
  {
    Header: "Started By",
    accessor: "by",
  },
  {
    Header: "Cancelled By",
    accessor: "cby",
  },
];

export const tmpForm = [
  {
    id: "1",
    name: "caption",
    label: "Recurring Payment amount?",
    type: "input",
    spacing: 12,
    required: true,
    showOther: false,
    length: "244",
  },
  {
    id: "2",
    name: "payment_amount",
    label: "Final providing Payment amount?",
    type: "input",
    spacing: 12,
    required: false,
    showOther: false,
    length: "244",
  },
];

export const tempChildHistoryData = [
  {
    id: "1",
    // name: "payment"
    code: "111",
    name: "Workflow History1",
    status: "Active",
    sdate: "11-2-2021",
    fdate: "",
    cdate: "12-4-2022",
    by: "Don",
    cby: "Zen",
  },
  {
    id: "2",
    // name: "Basic update"
    code: "222",
    name: "Workflow History2",
    status: "Draft",
    sdate: "11-2-2021",
    fdate: "16-10-2021",
    cdate: "12-4-2022",
    by: "Don",
    cby: "Sest",
  },
];
