export const ASSIGNED_ATTORNEYS = "ASSIGNED_ATTORNEYS";
export const ATTORNEY_ASSIGNED_FLAG = "ATTORNEY_ASSIGNED_FLAG";
export const ADD_ATTORNEY_INPUTS = "ADD_ATTORNEY_INPUTS";

export const ATTORNEY_SEARCH_LIST = "ATTORNEY_SEARCH_LIST";

export const EDIT_ATTORNEY_INPUTS="EDIT_ATTORNEY_INPUTS";

export const CANCEL_ATTORNEY_PAGE = "CANCEL_ATTORNEY_PAGE";

export const  ATTORNEY_TO_HISTORY = "ATTORNEY_TO_HISTORY";





